# Generated by Django 3.1 on 2020-09-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='oil',
            field=models.CharField(choices=[('5.000', 'miles'), ('10.000', 'miles'), ('15.000', 'miles'), ('20.000', 'miles'), ('25.000', 'miles'), ('30.000', 'miles'), ('35.000', 'miles'), ('40.000', 'miles'), ('45.000', 'miles'), ('50.000', 'miles'), ('55.000', 'miles'), ('60.000', 'miles')], default='5.000', max_length=7),
        ),
    ]
