# Generated by Django 3.1 on 2020-09-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='toys',
            field=models.ManyToManyField(to='main_app.Addon'),
        ),
    ]
