# Generated by Django 3.1 on 2020-09-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200922_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='tire_rotation',
        ),
    ]
